# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from res_rc import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)

        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 481))
        self.widget.setObjectName("widget")
        self.background = QtWidgets.QLabel(self.widget)
        self.background.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.background.setStyleSheet("border-image: url(:images/bg.png);\n"
"border-radius: 20px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.blackout = QtWidgets.QLabel(self.widget)
        self.blackout.setGeometry(QtCore.QRect(10, 10, 331, 461))
        self.blackout.setStyleSheet("background-color: rgba(0,0,0,100);\n"
"border-radius: 10px;")
        self.blackout.setText("")
        self.blackout.setObjectName("blackout")
        self.volume_slider = QtWidgets.QSlider(self.widget)
        self.volume_slider.setGeometry(QtCore.QRect(750, 9, 22, 461))
        self.volume_slider.setStyleSheet("QSlider::groove:vertical {\n"
"background-color: rgba(0,0,0,100);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"width: 10px;\n"
"height: 30px;\n"
"padding: 5px;\n"
"background-color: rgba(255, 33, 100, 230);\n"
"border-radius: 10px;\n"
"}")
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setObjectName("volume_slider")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 311, 451))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.widget1)
        self.listWidget.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(255, 33, 100, 230);\n"
"border-radius: 10px;\n"
"color: white;\n"
"padding: 5px;\n"
"font-size: 10pt;")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.frame = QtWidgets.QFrame(self.widget1)
        self.frame.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(255, 33, 100, 230);\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"font-size: 15pt;\n"
"color: rgba(255, 255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 33, 100, 100);\n"
"}")
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_sound_btn = QtWidgets.QPushButton(self.frame)
        self.add_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_sound_btn.setObjectName("add_sound_btn")
        self.horizontalLayout_2.addWidget(self.add_sound_btn)
        self.remove_sound_btn = QtWidgets.QPushButton(self.frame)
        self.remove_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_sound_btn.setObjectName("remove_sound_btn")
        self.horizontalLayout_2.addWidget(self.remove_sound_btn)
        self.verticalLayout.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.widget1)
        self.frame1.setStyleSheet("QPushButton {\n"
"background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(255, 33, 100, 230);\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 18pt;\n"
"color: rgba(255, 255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 33, 100, 100);\n"
"}")
        self.frame1.setObjectName("frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_sound_btn = QtWidgets.QPushButton(self.frame1)
        self.prev_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prev_sound_btn.setObjectName("prev_sound_btn")
        self.horizontalLayout.addWidget(self.prev_sound_btn)
        self.play_sound_btn = QtWidgets.QPushButton(self.frame1)
        self.play_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_sound_btn.setObjectName("play_sound_btn")
        self.horizontalLayout.addWidget(self.play_sound_btn)
        self.next_sound_btn = QtWidgets.QPushButton(self.frame1)
        self.next_sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_sound_btn.setObjectName("next_sound_btn")
        self.horizontalLayout.addWidget(self.next_sound_btn)
        self.verticalLayout.addWidget(self.frame1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_sound_btn.setText(_translate("Form", "ADD"))
        self.remove_sound_btn.setText(_translate("Form", "REMOVE"))
        self.prev_sound_btn.setText(_translate("Form", "<"))
        self.play_sound_btn.setText(_translate("Form", "PLAY"))
        self.next_sound_btn.setText(_translate("Form", ">"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
